<?php
function getDoctorSpecializations(): array {
    return [
        'General Physician',
        'Family Medicine Specialist',
        'Internal Medicine Specialist',
        'Cardiologist',
        'Cardiac Surgeon',
        'Hematologist',
        'Neurologist',
        'Neurosurgeon',
        'Psychiatrist',
        'Psychotherapist',
        'Clinical Psychologist',
        'Counselor',
        'Orthopedic Surgeon',
        'Rheumatologist',
        'Physiotherapist',
        'Pediatrician',
        'Neonatologist',
        'Gynecologist',
        'Obstetrician',
        'Fertility Specialist',
        'Dermatologist',
        'Cosmetologist',
        'Plastic Surgeon',
        'Ophthalmologist',
        'ENT Specialist',
        'Otolaryngologist',
        'Audiologist',
        'Dentist',
        'Orthodontist',
        'Oral Surgeon',
        'Pulmonologist',
        'Respiratory Therapist',
        'Gastroenterologist',
        'Hepatologist',
        'Nephrologist',
        'Urologist',
        'Endocrinologist',
        'Diabetologist',
        'Oncologist',
        'Radiation Oncologist',
        'General Surgeon',
        'Vascular Surgeon',
        'Thoracic Surgeon',
        'Trauma Surgeon',
        'Emergency Medicine Specialist',
        'Critical Care Specialist',
        'Anesthesiologist',
        'Infectious Disease Specialist',
        'Immunologist',
        'Allergist',
        'Radiologist',
        'Pathologist',
        'Microbiologist',
        'Geriatrician',
        'Rehabilitation Specialist',
        'Pain Management Specialist',
        'Ayurvedic Doctor',
        'Homeopathic Doctor',
        'Unani Specialist',
        'Siddha Doctor',
        'Naturopathy Specialist',
        'Nutritionist',
        'Dietitian',
        'Speech Therapist',
        'Occupational Therapist',
        'Sports Medicine Specialist',
        'Sleep Specialist',
    ];
}
